import React from "react"
import MathJaxComponent from "../../Components/MathJax"
import TestYourSelf from "../../Components/TestYourSelf/TestYourSelf"


export default function CG(){

    const CGContent =  `
        We say we have a cyclic group $G$ if we have the following: 
        \[
            G = \\{q^n \\ | \\ n \\in \\mathbb{Z}\\}  
        \]

      This is interpreted as $q$ is a generator of G. And the formula above
      says for any $q  \\in G$ if the whole set $G$ can be generated by
     $q$ to the power of any $n \\in \\mathbb{Z}$. \[\]

    What is the use of cyclic groups? 
    If you take a look at the Cryptographic topic, you'll already see that 
    all of the sections take use of cyclic groups, it is often a precondition
    that most of the public cryptographic algorithm uses. Here we will go further into
    Cyclic groups and look at some examples.  \[\]

    Here are some properties of cyclic groups: $\\\\$
    - Every cyclic group is abelian: $\\\\$
    Recall that abelian group is a group where the binary operation is commutative. (You can read more about Abelian groups in the group section).$\\\\$
    We know from the definition of a cyclig group: 
     \[
        G = \\{q^n \\ | \\ n \\in \\mathbb{Z}\\}  
    \]
    Now let $a,b$ be two elements in $G$ such that $a = q^i$ and $b = q^j$ for some $i, j \\in \\mathbb{Z}$$\\\\$
Then for multiplication: 
\[
    a \\cdot b = q^i \\cdot q^j = q^{i+j} = q^{j+i} = q^j \\cdot q^i = b \\cdot a
\]
For addition: 
\[
    a + b = qi + qj = qj + qi  = b + a
\]


`

    return(
        <div>
        <h3>In this section we will take a look at Cyclic Groups.</h3>
        <MathJaxComponent mathExpression={CGContent}/>
       <TestYourSelf themeInput = "CG" />
        </div>
    )
}